[package]
name = "rustygear"
version = "0.2.0"
authors = ["Clint Byrum <clint@fewbar.com>"]

[dependencies]
time = "0.1"
byteorder = "0.3"
uuid = "0.1"
hash_ring = "*"
log = "*"
env_logger = "*"
mio = "*"
