[package]
name = "rustygear"
version = "0.5.0"
authors = ["Clint Byrum <clint@fewbar.com>"]

[dependencies]
bytes = "*"
hash_ring = { git = "https://github.com/SpamapS/rust-hash-ring.git" }
log = "*"
env_logger = "*"
tokio-io = "*"
tokio-core = "*"
futures = "*"
uuid = { version = "*", features = ["v4"] }
