[package]
name = "rustygear"
version = "0.6.0"
authors = ["Clint Byrum <clint@fewbar.com>"]

[dependencies.tokio-util]
features = ["codec"]
version = "*"

[dependencies]
bytes = ">=0.5.0"
hash_ring = "*"
log = "*"
env_logger = "*"
futures = "*"
